language: php
env: 
  global:
    - PACKAGE_NAME=eu.painlessgaming.wcf.serverlist
php:
  - 5.6
before_install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  
script:
  - echo "\nBuilding acpTemplates.tar\n-------------------------" && cd acpTemplates && tar cvf ../acpTemplates.tar * && cd ..
  - echo "\nBuilding files.tar\n------------------" && cd files && tar cvf ../files.tar --exclude .DS_Store * && cd ..
  - echo "\nBuilding templates.tar\n----------------------" && cd templates && tar cvf ../templates.tar * && cd ..
  - echo "\nBuilding $PACKAGE_NAME archive"
  - tar -czvf $PACKAGE_NAME.tar.gz * --exclude=acpTemplates --exclude=files --exclude=templates --exclude=nbproject --exclude=README* --exclude=.gitignore --exclude=*.tar.gz --exclude=LICENSE* --exclude=c --exclude=z --exclude=v
 
after_success:
  - ftp -u ftp://$FTPUSER:$FTPPASS@$HOME/$TRAVIS_BUILD_NUMBER/$PACKAGE_NAME.tar.gz $PACKAGE_NAME.tar.gz
 
deploy:
  provider: releases
  api_key:
    secure: Ka2WG4MmJULgS3M9myjBOyfrIYG8+irhlsGJ0oUIe8b8OBruzsYOltIkC+g8j/m7gCr6E5XfxQOm/yd2ygOJIE0QXf9Wo9dU5dk3LWoCsHnNo2D5DFn7rGWR6NzNclEAcIAiZaS8xE8UE5MVjeOU0SyhQorTY+gH0VNZugwTT5jDEVc63Rj/CqIelyYt/J3$
  file: "$PACKAGE_NAME.tar.gz"
  skip_cleanup: true
  on:
    tags: true